name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run build script
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: rechenmodul-core
          path: dist/
